/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tfdatabase;

import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author serch
 */
public class Actualizar extends javax.swing.JFrame {

    String Departamento, Marcas, Articulo, Presio;
    
    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        this.setSize(500,365);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        this.setIconImage(getIconImage());
    }

    @Override
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("Images/Icon.png"));
   return retValue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SeleccArticulo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Marca = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        RAM = new javax.swing.JTextField();
        ROM = new javax.swing.JTextField();
        Nucleos = new javax.swing.JTextField();
        Frecuencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));

        jPanel1.setBackground(new java.awt.Color(70, 70, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Seleccione Departamento a Editar");

        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "smartphones", "procesadores" }));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cambie lo que desee actualizar");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Seleccione Nombre del Articulo a Editar");

        SeleccArticulo.setForeground(new java.awt.Color(204, 204, 204));
        SeleccArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Artículo" }));
        SeleccArticulo.setEnabled(false);
        SeleccArticulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SeleccArticuloItemStateChanged(evt);
            }
        });

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aplicar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Marca.setEnabled(false);

        Nombre.setEnabled(false);

        Precio.setEnabled(false);

        Stock.setEnabled(false);

        RAM.setEnabled(false);

        ROM.setEnabled(false);

        Nucleos.setEnabled(false);

        Frecuencia.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Marca");

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nombre");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Precio");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Stock");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("RAM");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ROM");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nucleos");

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Frecuencia");

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(Dept, 0, 257, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(SeleccArticulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(RAM, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(ROM))))
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nucleos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Frecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(Stock)))))
                    .addComponent(jLabel7))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ROM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccArticuloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SeleccArticuloItemStateChanged

    }//GEN-LAST:event_SeleccArticuloItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.SeleccArticulo.setEnabled(true);
        this.jButton2.setEnabled(true);
        Conectar cn = new Conectar();
        Statement st;
        ResultSet rs;
        Departamento=this.Dept.getSelectedItem().toString();
        System.out.println("Esta es la marca "+Marcas);
        try {
            this.SeleccArticulo.removeAllItems();
            st = (Statement) cn.con.createStatement();
            rs = st.executeQuery("SELECT * FROM `"+Departamento+"`");
            this.SeleccArticulo.addItem("Seleccione "+Departamento);
            while (rs.next()) {
                this.SeleccArticulo.addItem(rs.getString("Nombre"));
            }
            cn.con.close();
        } catch (Exception e) {
        }
        this.RAM.setText("");
        this.ROM.setText("");
        this.Marca.setText("");
        this.Nombre.setText("");
        this.Precio.setText("");
        this.Stock.setText("");
        this.Frecuencia.setText("");
        this.Nucleos.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Departamento=this.Dept.getSelectedItem().toString();
        if(Departamento.equals("procesadores")){
            this.Nombre.setEnabled(true);
            this.Marca.setEnabled(true);
            this.Precio.setEnabled(true);
            this.Stock.setEnabled(true);
            this.Frecuencia.setEnabled(true);
            this.Nucleos.setEnabled(true);
            this.RAM.setEnabled(false);
            this.ROM.setEnabled(false);
            Conectar cn = new Conectar();
            Statement st;
            ResultSet rs;
            try {
                st = (Statement) cn.con.createStatement();
                rs = st.executeQuery("SELECT * FROM `procesadores` WHERE `Nombre` LIKE '" + this.SeleccArticulo.getSelectedItem().toString() + "'");
                while (rs.next()) {
                    this.Marca.setText(rs.getString("Marca"));
                    this.Nombre.setText(rs.getString("Nombre"));
                    this.Nucleos.setText(rs.getString("Nucleos"));
                    this.Precio.setText(rs.getString("Precio"));
                    this.Frecuencia.setText(rs.getString("Frecuencia"));
                    this.Stock.setText(rs.getString("Stock"));
                }
                cn.con.close();
            } catch (Exception e) {
            }
        }
        if(Departamento.equals("smartphones")){
            this.Nombre.setEnabled(true);
            this.Marca.setEnabled(true);
            this.Precio.setEnabled(true);
            this.Stock.setEnabled(true);
            this.RAM.setEnabled(true);
            this.ROM.setEnabled(true);
            this.Frecuencia.setEnabled(false);
            this.Nucleos.setEnabled(false);
            Conectar cn = new Conectar();
            Statement st;
            ResultSet rs;
            try {
                st = (Statement) cn.con.createStatement();
                rs = st.executeQuery("SELECT * FROM `smartphones` WHERE `Nombre` LIKE '" + this.SeleccArticulo.getSelectedItem().toString() + "'");
                while (rs.next()) {
                    this.Marca.setText(rs.getString("Marca"));
                    this.Nombre.setText(rs.getString("Nombre"));
                    this.Precio.setText(rs.getString("Precio"));
                    this.RAM.setText(rs.getString("RAM"));
                    this.ROM.setText(rs.getString("ROM"));
                    this.Stock.setText(rs.getString("Stock"));
                }
                cn.con.close();
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Conectar cn=new Conectar();
        Statement st;
        ResultSet rs;
        if(Departamento.equals("smartphones")){
            try {
                st = (Statement) cn.con.createStatement();
                st.executeUpdate("UPDATE smartphones SET Marca='"+this.Marca.getText()+"',Nombre='"+this.Nombre.getText()+"',Precio="+this.Precio.getText()+",RAM="+this.RAM.getText()+",ROM="+this.ROM.getText()+", Stock="+this.Stock.getText()+" WHERE `Nombre` LIKE '"+this.SeleccArticulo.getSelectedItem().toString()+"'");
                JOptionPane.showMessageDialog(null, "Datos Actualizados exitosamente");
                cn.con.close();
                this.RAM.setText("");
                this.ROM.setText("");
                this.Marca.setText("");
                this.Nombre.setText("");
                this.Precio.setText("");
                this.Stock.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No pongas letras donde van numeros");
            }
        }
        if(Departamento.equals("procesadores")){
            try {
                st = (Statement) cn.con.createStatement();
                st.executeUpdate("UPDATE procesadores SET Marca='"+this.Marca.getText()+"',Nombre='"+this.Nombre.getText()+"',Nucleos="+this.Nucleos.getText()+",Frecuencia="+this.Frecuencia.getText()+",Precio="+this.Frecuencia.getText()+", Stock="+this.Stock.getText()+" WHERE `Nombre` LIKE '"+this.SeleccArticulo.getSelectedItem().toString()+"'");
                JOptionPane.showMessageDialog(null, "Datos Actualizados exitosamente");
                cn.con.close();
                this.Frecuencia.setText("");
                this.Nucleos.setText("");
                this.Marca.setText("");
                this.Nombre.setText("");
                this.Precio.setText("");
                this.Stock.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No pongas letras donde van numeros");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu menu=new Menu();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Frecuencia;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nucleos;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField RAM;
    private javax.swing.JTextField ROM;
    private javax.swing.JComboBox<String> SeleccArticulo;
    private javax.swing.JTextField Stock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
